options:
  libPath: "/appdata/users/P100068/R/libs"
  home_dir: "/home/P100068/lindas"

paths:
  resources: "RESOURCES/"
  scripts_dir: "scripts/"
  input_dir: "DATA/"
  output_dir: "RESULTS/"
  
  

files:
  input: "AMLMRD_curated_seuratObject.Rds"
  
steps:
  - "01-QC_RNA"
  - "02-QC_ADT"
  - "03-gene_cell_filtering"
  - "04-RNA_norm"
  - "05-ADT_norm"
  - "06-dim_reduction"
  
analysis:
  qc:
    min_nFeature_per_cell: 750
    max_nFeature_per_cell: 6000
    max_mito: 15
    max_ribo: 30
    max_ncount: 30000
    min_ncount: 0
  norm:
    method_norm: "SCTransform_classic"       #classic / SCTransform_split / SCTransform_classic
    n_var_features: 3000
    vars_to_regress: "nCount_RNA"
    samples: "DonorID"
  
  dim_reduction:
    method_neighbors: "multimodal"        #pca / apca / multimodal
    n_pcs_RNA: 30
    n_pcs_ADT: 10
    harmony: TRUE

  clustering:
    resolution: 0.8
    pcs: 30
  
  metadata:
    batchvar: "RunID.x"
    batchvar2: "RunID.y"
    donors: "DonorID"       #3
    timepoint: "Group"      #3
    samples: "Description"  #9
  